export const allMenuItems = [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: "FaChartSimple",
    path: "/dashboard",
    roles: ["Admin", "manager"],
    withSub: false,
  },
  {
    id: "destinations",
    title: "Destinations",
    icon: "FaCity",
    path: "/destinations",
    roles: ["Admin", "manager"],
    withSub: true,
  },
  {
    id: "trips",
    title: "Trips",
    icon: "FaShip",
    path: "/trips",
    roles: ["Admin", "manager", "editor"],
    withSub: true,
  },
  {
    id: "transfer",
    title: "Transfer Category",
    icon: "FaCar",
    path: "/transfer",
    roles: ["Admin", "manager", "sales"],
    withSub: true,
  },
  {
    id: "facility",
    title: "Facility Setting",
    icon: "FaInfo",
    path: "/facility",
    roles: ["Admin", "manager", "sales"],
    withSub: false,
  },
  {
    id: "Booking",
    title: "Booking",
    icon: "FaTicketAlt",
    path: "/Booking",
    roles: ["Admin", "manager", "sales"],
    withSub: false,
  },
  {
    id: "exchangeRates",
    title: "Exchange Rates",
    icon: "FaDollarSign",
    path: "/exchange-rates",
    roles: ["Admin", "manager"],
    withSub: false,
  },
  {
    id: "Users",
    title: "Users",
    icon: "FiUsers",
    path: "/Users",
    roles: ["Admin", "manager", "sales"],
    withSub: false,
  },
  // {
  //   id: "transfer",
  //   title: "Transfer Category",
  //   icon: "FaCar",
  //   path: "/transfer",
  //   roles: ["Admin", "manager", "sales"],
  //   withSub: false,
  // },
];

export const SubMenuItems = [
  {
    id: "destinationsImgs",
    parentId: "destinations",
    title: "Images",
    icon: "FaFileImage",
    path: "/destinations/images",
    roles: ["Admin", "manager"],
  },
  {
    id: "tripsImgs",
    parentId: "trips",
    title: "Images",
    icon: "FaFileImage",
    path: "/trips/images",
    roles: ["Admin", "manager"],
  },
  {
    id: "transferImgs",
    parentId: "transfer",
    title: "Images",
    icon: "FaFileImage",
    path: "/transfer/images",
    roles: ["Admin", "manager", "sales"],
  },
  {
    id: "tripsTrans",
    parentId: "trips",
    title: "Translations",
    icon: "FaGlobe",
    path: "/trips/translation",
    roles: ["Admin", "manager"],
  },
  {
    id: "prices",
    parentId: "trips",
    title: "Prices",
    icon: "FaDollarSign",
    path: "/trips/prices",
    roles: ["Admin", "manager"],
  },
  {
    id: "pickups",
    parentId: "trips",
    title: "Pick Ups",
    icon: "FaMapMarked",
    path: "/trips/pickups",
    roles: ["Admin", "manager"],
  },
  {
    id: "facility",
    parentId: "trips",
    title: "facility",
    icon: "FaInfo",
    path: "/trips/Facility",
    roles: ["Admin", "manager"],
  },
];
